# Generated by Django 5.0.7 on 2024-07-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ricovero',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='cittadino',
            table='Cittadino',
        ),
    ]
