# Generated by Django 5.0.7 on 2024-07-25 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0002_alter_ricovero_data_alter_cittadino_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ospedale',
            table='Ospedale',
        ),
        migrations.AlterModelTable(
            name='patologia',
            table='Patologia',
        ),
        migrations.AlterModelTable(
            name='patologiacronica',
            table='PatologiaCronica',
        ),
        migrations.AlterModelTable(
            name='patologiamortale',
            table='PatologiaMortale',
        ),
        migrations.AlterModelTable(
            name='patologiaricovero',
            table='PatologiaRicovero',
        ),
        migrations.AlterModelTable(
            name='ricovero',
            table='Ricovero',
        ),
    ]
