# Generated by Django 5.0.7 on 2024-07-25 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0003_alter_ospedale_table_alter_patologia_table_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='patologiaricovero',
            unique_together=set(),
        ),
    ]
