# Generated by Django 5.0.7 on 2024-07-25 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0004_alter_patologiaricovero_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ospedale',
            name='direttoreSanitario',
            field=models.ForeignKey(db_column='direttoreSanitario', on_delete=django.db.models.deletion.PROTECT, to='importer.cittadino'),
        ),
        migrations.AlterUniqueTogether(
            name='patologiaricovero',
            unique_together={('codOspedale', 'codRicovero', 'codPatologia')},
        ),
    ]
