# Generated by Django 5.0.7 on 2024-07-25 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0005_alter_ospedale_direttoresanitario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patologiacronica',
            name='codPatologia',
            field=models.OneToOneField(db_column='codPatologia', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='importer.patologia'),
        ),
        migrations.AlterField(
            model_name='patologiamortale',
            name='codPatologia',
            field=models.OneToOneField(db_column='codPatologia', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='importer.patologia'),
        ),
        migrations.AlterField(
            model_name='patologiaricovero',
            name='codOspedale',
            field=models.ForeignKey(db_column='codOspedale', on_delete=django.db.models.deletion.CASCADE, to='importer.ospedale'),
        ),
        migrations.AlterField(
            model_name='patologiaricovero',
            name='codPatologia',
            field=models.ForeignKey(db_column='codPatologia', on_delete=django.db.models.deletion.CASCADE, to='importer.patologia'),
        ),
        migrations.AlterField(
            model_name='patologiaricovero',
            name='codRicovero',
            field=models.ForeignKey(db_column='codRicovero', on_delete=django.db.models.deletion.CASCADE, to='importer.ricovero'),
        ),
    ]
