# Generated by Django 5.0.7 on 2024-07-25 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0006_alter_patologiacronica_codpatologia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ricovero',
            name='codOspedale',
            field=models.ForeignKey(db_column='codOspedale', on_delete=django.db.models.deletion.CASCADE, to='importer.ospedale'),
        ),
        migrations.AlterField(
            model_name='ricovero',
            name='paziente',
            field=models.ForeignKey(db_column='paziente', on_delete=django.db.models.deletion.CASCADE, to='importer.cittadino'),
        ),
    ]
