# Generated by Django 5.0.7 on 2024-07-25 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0008_alter_patologiaricovero_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patologiaricovero',
            options={},
        ),
    ]
