# Generated by Django 5.0.6 on 2024-06-03 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cittadino',
            fields=[
                ('CSSN', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('dataNascita', models.DateField()),
                ('luogoNascita', models.CharField(max_length=100)),
                ('indirizzo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ospedale',
            fields=[
                ('codice', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('città', models.CharField(max_length=100)),
                ('indirizzo', models.CharField(max_length=200)),
                ('direttoreSanitario', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patologia',
            fields=[
                ('cod', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('criticità', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PatologiaCronica',
            fields=[
                ('codPatologia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.patologia')),
            ],
        ),
        migrations.CreateModel(
            name='PatologiaMortale',
            fields=[
                ('codPatologia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.patologia')),
            ],
        ),
        migrations.CreateModel(
            name='Ricovero',
            fields=[
                ('cod', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('durata', models.IntegerField()),
                ('motivo', models.TextField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('codOspedale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ospedale')),
                ('paziente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.cittadino')),
            ],
        ),
        migrations.CreateModel(
            name='PatologiaRicovero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codOspedale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ospedale')),
                ('codPatologia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.patologia')),
                ('codRicovero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ricovero')),
            ],
        ),
    ]
